### ISSUE TITLE
Expandable header navigation items should "close" on second click

### ISSUE THREAD

**Issue by pretzL** [Fermain/-mollify#108]
As it is now, if you press the menu icon or the search icon, they change the app state, but clicking again does nothing. Second click should bring the user back to where they were before. The search icon changes the URL path but the menu is just an overlay.
Additionally, the settings icon menu seems to have a pretty long delay on the fade-out animation. It feels a tad clunky on mobile. Maybe it would overall look and feel better if the animation was a slide instead?

**Comment by Fermain** [comment]
After side nav click, close the side nav (on mobile)
