### ISSUE TITLE
Active mode set on content nav when active

### ISSUE THREAD

**Issue by pretzL** [Fermain/-mollify#109]
The navigation menu should reflect which bit of content is currently active. It should also persist the accordion state for whichever content item is currently being viewed, i.e. the navigation should stay open on that lesson if the navigation is opened after navigating.
As it is now, once you close the navigation it also collapses all accordions.

**Comment by Fermain** [comment]
For now only match the exact path, i.e. the exact lesson/module or course that's currently being viewed.
