### ISSUE TITLE
Close navigation when item has been clicked

### ISSUE THREAD

**Issue by pretzL** [Fermain/-mollify#110]
The navigation bar persist open when an item has been clicked on mobile screens. This is poor UX as it then requires an extra click just to view the content you wanted to view. It should persist open on desktop as we have the screen real estate available for it, but this should not be the case on mobile screens.

**Comment by Fermain** [comment]
Hi, is this related to the open PR? Could you link the branch in the side menu here:

<img width="315" alt="image" src="https://github.com/Fermain/-mollify/assets/10801540/037e48f0-61e1-4798-b166-17de52d18d61">

**Comment by Ousman37** [comment]
https://github.com/Fermain/-mollify/tree/fix-navigation-ux
