### ISSUE TITLE
Clicking the lesson navigation second level items does nothing

### ISSUE THREAD

**Issue by pretzL** [Fermain/-mollify#111]
See attached image. If any of the numbered items are clicked (e.g. `Using a single object to create HTML`, you are not scrolled to the respective heading in the same way you are if you click any of the unnumbered headings (e.g. `Loading multiple JavaScript files`

![image](https://github.com/Fermain/-mollify/assets/30121693/b3c70a26-57c3-4534-a7ec-92c2510e1da9)

**Comment by Fermain** [comment]
This is not fixed, but I disabled h3s
