### ISSUE TITLE
Copy paste functionality for code blocks

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#122]
Wrap code blocks in a svelte element (or use remark plugin) to create a button allowing for copy/pasting of markdown code blocks.

**Comment by Fermain** [comment]
Whoever takes this task, please do some additional research on any other way we can jazz up code blocks.

**Comment by Fermain** [comment]
<img width="699" alt="image" src="https://github.com/Fermain/-mollify/assets/10801540/14dcc6ae-1742-4714-9842-83eeac23711f">

**Comment by Fermain** [comment]
Suggest using a remark plugin.

**Comment by StianSto** [comment]
Who would have thought making a single button would be this hard 😆 

i have made a viable product that utilizes sketons own CodeBlock component together with a custom remark plugin. we can create our own component in the future as well 😄  
<img src="https://user-images.githubusercontent.com/95475303/267625559-70622cfe-a58a-42f1-ae60-a029555c135c.png" alt="Screenshot 2023-09-13 124142" width="50%">

BUT there are still a few limitations that i think we can iron out before i push the code. to make this work we need to import the component to the +page.md file we are in. im open to any ideas to have we can do this better, to minimize the work for content creators
![Screenshot 2023-09-13 133347](https://github.com/Fermain/-mollify/assets/95475303/2fe3d587-466a-4ed0-9843-498eee7ef944)

what is so nice about this method is that it is now very easy to create other custom components, if we can figure out how to do the imports in a nice and stressfree way. it is technically possible to just write <CodeBlock> in the .md file, but i gather that it is best to keep it as native markdown if possible

**Comment by StianSto** [comment]
will give this a shot as well and see if that works better: https://prismjs.com/plugins/copy-to-clipboard/
