### ISSUE TITLE
UI/UX: Right meny needs better organizing

### ISSUE THREAD

**Issue by mitthrawnuruodo** [Fermain/-mollify#127]
The menu on the right-hand side becomes less organized when you have multiple courses, modules, or lessons open. The subtle extra padding isn't enough to keep track of where you are.

**Comment by Fermain** [comment]
I agree, do you have an idea for how to make this hierarchy more obvious?

**Comment by Fermain** [comment]
This issue needs design thinking.

**Comment by ShaindalDev** [comment]
@lysaker-git is looking at this issue at the moment
