### ISSUE TITLE
View course progress indicators or completion status

### ISSUE THREAD

**Issue by ShaindalDev** [Fermain/-mollify#139]
Have to option to view the course progress with a % bar. Like an loading bar that will increase as you completed more and more of the course

**Comment by Fermain** [comment]
Key question here, what does completion mean?

**Comment by Fermain** [comment]
Where do we store this data? Local storage?

We don't have a database, so storing on the backend is not really an option - unless of course we implement sqlite which be a whole sprints worth of work.
