### ISSUE TITLE
poor or missing documentation

### ISSUE THREAD

**Issue by StianSto** [Fermain/-mollify#144]
some of the packages have poor or missing documentation. this leads newcomers to spend hours trying and failing while figuring out how each package works. these are the ones i found with missing documentation and instructions: 

- [x] molly
- [ ] flow
- [x] lms

**Comment by MegumiKim** [comment]
Also, documentation in the project's root folder needs to be updated.

**Comment by ShaindalDev** [comment]
@Fermain Is there written docs for the project?

**Comment by Anclagen** [comment]
I'm just making some updates to the read me, and added some more scripts to the package json in the main repo to make things easier [here](https://github.com/Fermain/-mollify/tree/read-me-updates). I can also add a little content in the LMS readme about content creation for testing, if you want some test content as an example to look at I have some [here](https://github.com/Anclagen/-mollify/tree/deploy-test/packages/lms/src/routes/content) in my fork

**Comment by Fermain** [comment]
> @Fermain Is there written docs for the project?

Negativo

**Comment by Anclagen** [comment]
PR #150 has been merged this updates;
- Main README updated for developers with instructions for install, setup, usage and content creation.
- LMS README updated with a draft of a possible workflow for installing as an npm package, this is not currently functional.
- Some minor updates to tts, molly and cli README files but these need further fleshing out

We (@MegumiKim) have also started testing out and organsing the [docs package](https://github.com/Fermain/-mollify/tree/docs-nextra)  but this can start to really be fleshed out once package are ready for installation through npm.

**Comment by pretzL** [comment]
@StianSto is this issue resolved with #150 or is there something left to do?

**Comment by StianSto** [comment]
yes, i am very happy with the new changes. great work! 

im closing this issue, since it is kind of a large one. instead we can start if I (or anyone else) find a specific issue related to documentation, its better to add specific documentation issues to the board, instead of keeping this one open :) thanks for the reminder 😅 

i see flow still has a boilerplate readme, but then again it isnt finished yet i believe

**Comment by MegumiKim** [comment]
As Alex mentioned above, we started a doc packages in relation to this issue and I added some contents in it. But since it is not needed yet, I put it aside. I will create an issue so that someone can take it over when the time comes...
