### ISSUE TITLE
Table of content in mobile view taking full screen

### ISSUE THREAD

**Issue by MegumiKim** [Fermain/-mollify#148]
Lesson Index(?) is creating an empty space/gap on mobile screen. 
This does not look good especially on the landing page. I think it just needs a height:min-content. 

![Screenshot 2023-09-22 at 09 32 33](https://github.com/Fermain/-mollify/assets/64102873/c7166bb4-534b-4815-b06a-d60097c33036)

**Comment by ShaindalDev** [comment]
I believe that this can be fixed when we get the new prototype.
