### ISSUE TITLE
Start creating a preliminary documentation set for the project

### ISSUE THREAD

**Issue by ShaindalDev** [Fermain/-mollify#151]
Documentation set for the project. Some is written allready and PR for it can be found [here](https://github.com/Fermain/-mollify/pull/150). This issue is a task that will continue past sprint 1 since the documentation will continue to grow until it's finished.

**Comment by Anclagen** [comment]
I assume this task should encompass issue #144 as well with are primary goals being to update all the package read me files. I think the main repo read me should direct developer working with the project and the individual package read me files should be geared towards and npm style read me guide.

- [ ] Main Repo
- [ ] CLI
- [ ] Flow
- [ ] LMS
- [ ] Molly
- [ ] TTS
- [ ] Types

I'm also wondering if we should setup the docs package to run through the LMS to provide documentation or set it up to run as a separate entity similar to the lms, I'm sure we can find a package to create a standard docs layout then fill up the content with more specific information on using various packages as they are built.
