### ISSUE TITLE
Move add bookmark icon next to lesson title

### ISSUE THREAD

**Issue by MegumiKim** [Fermain/-mollify#185]
While waiting for the new prototype, I would like to propose to move the add bookmark icon right next to each lesson title.
![Screenshot 2023-09-22 at 09 41 42](https://github.com/Fermain/-mollify/assets/64102873/56008cb0-630c-4e70-b786-286dfebccd5b)

**Comment by pretzL** [comment]
As an initial reaction I agree with you. I think however we should do some research on the UX front for this as I'm sure there is some data on the positioning of such page elements. Perhaps we can conduct some questionnaire type thing with the users who currently use Mollify to query some of the things we're unsure of, like the positioning of the bookmarks icon or the search bar etc.

**Comment by MegumiKim** [comment]
Good idea :-) 
Since the new prototype is not likely coming as expected, there is a room for some UX research including questionnaire and user testing.
