### ISSUE TITLE
Add navigation query string flag options

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#188]
Add these querystring options to change the way that the nav is rendered:

- [ ] `?nav=institution` Same as current default behaviour
- [ ] `?nav=programme` Shows the current Programme level entity and all children
- [ ] `?nav=course` Shows the current Course level entity and all children
- [ ] `?nav=module` Shows the current Module level entity and all children
- [ ] `?nav=disabled` Disabled the navigation entirely

**Comment by MegumiKim** [comment]
@StianSto I started working on it this but I am having a difficulty understanding the logic inside nav/entity (sorry...) and I am afraid of breaking what you just fixed.
Could you perhaps take a look if you have a spare time? I am guessing it's a lot easier for you to complete this task...

**Comment by StianSto** [comment]
no problem i'll take a look at it :D
