### ISSUE TITLE
Feature: LMS global theming

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#22]
**Notes:**

At this stage Mollify requires a highly functional theme that is capable of ensuring maximum readability on all screen sizes. Design refinement will take place at a later date with cooperation from other departments.

**Design Guide:**
- High contrast with no risks taken around WCAG
- Dark/Light theme option (we could also look into a low-blue theme for minimising eye strain)
- Maximum content container width of `80ch`
- Prefer CSS grid over flex for 2D layout tasks

**Suggested subtasks:**

- [x] Establish a styling strategy (framework, preprocessor, approach)
- [x] Create a +layout.svelte component to govern global layout
- [x] Create a list of required core components (Header, Footer, Navigation, Reader, Tags, etc)
- [x] Scaffold the components folder with a standardised naming approach
- [x] Render a sample markdown page containing all possible markdown tags for demo/testing

V4 Grid layout:

![Image](https://user-images.githubusercontent.com/10801540/232696588-9f4e3e1d-6cec-487d-8d8f-011ec37cfabe.png)

```css
grid-template-columns: 2rem 1fr 3.75rem;
grid-template-rows: 2rem auto 1fr auto;
grid-template-areas:
        "brand reader settings"
        "brand tbc tbc"
        ". main main"
        "footer footer footer";
```

**Comment by Fermain** [comment]
This codepen was used to guide the direction of the layout: https://codepen.io/Fermain/pen/GRYmEea

@pretzL please summarise the work you did on this feature and we can close it.

**Comment by pretzL** [comment]
In this feature, the basis for a styling strategy has been set using SASS. This PR introduces a general platform for global styling as well as styling on the component level for the global theme. It creates a color system which generates necessary variations as well as sets the basic layout for the theme. The `+layout` component governs the global layout 

In this feature you will also find pre-created core components which fit into the layout and together create the global theme. These components are modular, so they can be swapped out to your liking, just edit the grid-template and the component imports in `+layout`.

Folders have been scaffolded using a very basic, but intuitive naming approach for ease of use and editing later on.

A sample markdown page containing all possible markdown tags for demo/testing has been added to the project and can be rendered as necessary.
