### ISSUE TITLE
Feature: LMS Content Dependencies

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#24]
The existing system (V3) uses a system for restricting search to lessons that have not already been accessed. This system is far from perfect and requires a lot of management.

In V5 I propose that content dependencies are handed at all levels:
- Lessons can depend on other lessons **in the same module**
- Modules can depend on other modules **in the same course**
- Courses can depend on other courses **in the same programme**
- Programmes cannot depend on each other

For now this meta field is being called `dependencies` but this might need to change. It could be called `dependsOn` or `previous`.

```yml
title: Another Example Lesson
type: lesson
previous: Example Lesson
```

**Comment by Anclagen** [comment]
- Updated parsing file structure output to use arrays and a children key.
- Implement dependency sorting of children during file structure parsing.
- Updated current page data sorting to get the currently viewed pages data.
- Updated 3 navigation components to use new file structure.

**Comment by Anclagen** [comment]
- ContentNav, now outputs course and recursive navs separately 
- Merged in types and updated code to use imported types from the types package.
