### ISSUE TITLE
Implement Skeleton framework

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#57]
Implement https://www.skeleton.dev/ on the existing LMS project by installing and importing styles. I suggest setting up a fresh project using `npm create` in order to see how the default configuration looks.

We can then implement the app shell and navigation features as the first step. To start with let's use a stock skeleton theme and we can use the theming tool https://www.skeleton.dev/ to create our own default theme.

**Comment by Fermain** [comment]
I'd like to start off with a fairly plain white and red Noroff vibe:



![Image](https://github.com/Fermain/-mollify/assets/10801540/e3e9ec33-672c-43ec-a955-3e3fe6ad5071)

**Comment by Melisa-Zorraindo** [comment]
I thought it could be useful to have a list of tasks to better track our progress. Feel free to add more tasks as you find them.

- [x] Implement app shell
- [ ] Style navigation
- [x] Implement app bar (styles header component)
- [x] Style settings component
- [x] Implement dark mode
- [x] Implement increase and decrease in font size
- [x] Style logo
- [ ] Style reader
- [ ] Style search component / Implement autocomplete - Styling done and works as intended, autocomplete will be explored by @pretzL 
- [ ] Style Molly chat window ([check this out](https://www.skeleton.dev/elements/chat))
- [ ] Style Main component ([check this out](https://tailwindcss.com/docs/typography-plugin))
- [ ] Style search page
