### ISSUE TITLE
Add keyboard navigation support to autocomplete feature

### ISSUE THREAD

**Issue by Melisa-Zorraindo** [Fermain/-mollify#64]
**Problem**

Currently, our search component includes an autocomplete feature that can only be navigated using a mouse, which poses accessibility challenges for keyboard users. This limitation prevents users who rely on keyboard navigation, such as individuals with motor disabilities or those who prefer using keyboard shortcuts, from effectively utilising the autocomplete feature.

**Solution**

To improve accessibility we can add keyboard navigation support that will allow users to navigate through the suggestions and select the desired option using their keyboards.

**Comment by pretzL** [comment]
I'm currently able to navigate the lookahead with tab, arrow keys and selecting with enter. Is there something else we need to add?

**Comment by pretzL** [comment]
The use of the `<Autocomplete />` Skeleton component already offers sufficient accessibility

**Comment by pretzL** [comment]
I'm going to reopen this since we have moved away from the `<Autocomplete />` component Skeleton offers due to severe interference with the search functionality, in particular the leet search functionality.
This should be looked into in order to ensure an accessible search system.

**Comment by Anclagen** [comment]
Yeah I think we should probably use anchor tags for the drop down results, and some support for tabbing away should be added as at the moment I can click away and the results disappear but if I use the keyboard to navigate away the search results remain.

**Comment by Melisa-Zorraindo** [comment]
I'm closing this issue as it was solved on PR#116
